# Generated by Django 5.2.5 on 2026-01-22 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='bank.wallet'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='workspace_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='bank.workspacewallet'),
        ),
    ]
