# Generated by Django 5.2.5 on 2026-01-11 13:14

import core.mixins
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('workspace_admin', 'Workspace Admin')], default='user', help_text='User role in the system', max_length=20)),
                ('is_business_email', models.BooleanField(default=False, help_text='Whether email is a business email (not free provider)')),
                ('business_domain', models.CharField(blank=True, help_text='Business email domain', max_length=255, null=True)),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Whether user has completed onboarding')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('force_password_change', models.BooleanField(default=False, help_text='Force user to change password on next login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], default='hourly', help_text='Preferred booking duration type', max_length=20)),
                ('preferred_space_types', models.JSONField(blank=True, default=list, help_text='List of preferred space types')),
                ('preferred_capacity_min', models.IntegerField(default=1, help_text='Minimum preferred space capacity')),
                ('preferred_capacity_max', models.IntegerField(default=10, help_text='Maximum preferred space capacity')),
                ('preferred_cities', models.JSONField(blank=True, default=list, help_text='List of preferred cities')),
                ('max_distance_km', models.FloatField(blank=True, default=10.0, help_text='Maximum distance from user location in kilometers', null=True)),
                ('preferred_amenities', models.JSONField(blank=True, default=list, help_text='List of must-have amenities')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget per booking', max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget per booking', max_digits=10, null=True)),
                ('preferred_days_of_week', models.JSONField(blank=True, default=list, help_text='Preferred days of week (0=Sunday, 6=Saturday)')),
                ('preferred_start_time', models.TimeField(blank=True, help_text='Preferred booking start time', null=True)),
                ('preferred_end_time', models.TimeField(blank=True, help_text='Preferred booking end time', null=True)),
                ('notify_recommendations', models.BooleanField(default=True, help_text='Receive space recommendations')),
                ('notify_price_drops', models.BooleanField(default=True, help_text='Notify about price drops')),
                ('notify_new_spaces', models.BooleanField(default=True, help_text='Notify about new spaces')),
                ('auto_suggest_similar', models.BooleanField(default=True, help_text='Auto-suggest similar spaces')),
                ('save_search_history', models.BooleanField(default=True, help_text='Save search history')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preference',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_verification_code',
                'ordering': ['-created_at'],
            },
        ),
    ]
