# Generated by Django 5.2.5 on 2025-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_verificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
