# Generated by Django 5.2.5 on 2025-10-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_verificationcode_options_user_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Force user to change password on next login'),
        ),
    ]
