# Generated by Django 5.2.5 on 2025-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_user_groups_user_is_staff_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
