# Generated by Django 5.2.5 on 2026-01-11 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('channels', models.JSONField(default=list, help_text='List of channels to send to: ["email", "push", "in_app"]')),
                ('target_roles', models.JSONField(default=list, help_text='Target specific roles: ["admin", "manager", "staff", "user"]')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broadcast Notification',
                'verbose_name_plural': 'Broadcast Notifications',
                'db_table': 'broadcast_notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('qr_code_generated', 'QR Code Generated'), ('qr_code_expired', 'QR Code Expired'), ('order_created', 'Order Created'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('booking_check_in', 'Check-in Reminder'), ('booking_completed', 'Booking Completed'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('system_alert', 'System Alert')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data (e.g., order_id, qr_code_id)')),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False, help_text='For push notifications')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='pending', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('response_code', models.CharField(blank=True, help_text='HTTP or gateway response code', max_length=50)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_qr_code', models.BooleanField(default=True, help_text='Send QR codes via email')),
                ('email_order_confirmation', models.BooleanField(default=True)),
                ('email_payment_confirmation', models.BooleanField(default=True)),
                ('email_booking_reminder', models.BooleanField(default=True)),
                ('email_booking_update', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_qr_code', models.BooleanField(default=False)),
                ('sms_booking_reminder', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('push_qr_code', models.BooleanField(default=False)),
                ('push_booking_reminder', models.BooleanField(default=False)),
                ('push_booking_update', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_qr_code', models.BooleanField(default=True)),
                ('in_app_booking_reminder', models.BooleanField(default=True)),
                ('in_app_booking_update', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest')], default='immediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
    ]
