# Generated by Django 5.2.5 on 2026-01-11 13:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingQRCodeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_device_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_device_user_agent', models.TextField(blank=True, null=True)),
                ('scan_result', models.CharField(choices=[('success', 'Success'), ('invalid', 'Invalid'), ('expired', 'Expired'), ('already_verified', 'Already Verified')], default='success', max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'qr_code_scan_log',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(help_text='When the user checked in')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='When the user checked out', null=True)),
                ('duration', models.DurationField(blank=True, help_text='Duration of stay (auto-calculated after checkout)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='checked_in', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qr_code_check_in',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField()),
                ('qr_code_image_url', models.URLField(blank=True, help_text='URL to QR code image stored in Appwrite', null=True)),
                ('appwrite_file_id', models.CharField(blank=True, help_text='File ID in Appwrite storage', max_length=255, null=True)),
                ('verification_code', models.CharField(help_text='Unique code for QR verification', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent to User'), ('scanned', 'Scanned'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('scan_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_by_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='QR code expiry time for check-in', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qr_code_order_qrcode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField()),
                ('qr_code_image_url', models.URLField(blank=True, help_text='URL to QR code image stored in Appwrite', null=True)),
                ('appwrite_file_id', models.CharField(blank=True, help_text='File ID in Appwrite storage', max_length=255, null=True)),
                ('verification_code', models.CharField(help_text='Unique code for QR verification', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent to User'), ('scanned', 'Scanned'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('used', models.BooleanField(default=False, help_text='True after booking is completed/checked out')),
                ('total_check_ins', models.IntegerField(default=0, help_text='Total check-in events (for monthly bookings)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_check_ins', models.IntegerField(blank=True, help_text='Maximum check-ins allowed (for monthly bookings)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('scan_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_by_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='QR code expiry time (usually checkout time)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='booking.booking')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_qr_codes', to='payment.order')),
            ],
            options={
                'db_table': 'qr_code_booking_qrcode',
                'ordering': ['-created_at'],
            },
        ),
    ]
