# Generated by Django 5.1.6 on 2025-11-25 19:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField()),
                ('qr_code_image', models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/')),
                ('verification_code', models.CharField(help_text='Unique code for QR verification', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent to User'), ('scanned', 'Scanned'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('scan_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_by_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='QR code expiry time for check-in', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='payment.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_code_order_qrcode',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_device_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_device_user_agent', models.TextField(blank=True, null=True)),
                ('scan_result', models.CharField(choices=[('success', 'Success'), ('invalid', 'Invalid'), ('expired', 'Expired'), ('already_verified', 'Already Verified')], default='success', max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='qr_code.orderqrcode')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_code_scan_log',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['order'], name='qr_code_ord_order_i_187545_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['verification_code'], name='qr_code_ord_verific_ed1ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['status'], name='qr_code_ord_status_a4e24a_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescanlog',
            index=models.Index(fields=['qr_code', 'scanned_at'], name='qr_code_sca_qr_code_1baaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcodescanlog',
            index=models.Index(fields=['scanned_by'], name='qr_code_sca_scanned_4fa7d5_idx'),
        ),
    ]
