# Generated by Django 5.1.6 on 2025-11-28 20:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_guest_verification_code_default'),
        ('payment', '0001_initial'),
        ('qr_code', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code_data', models.TextField()),
                ('qr_code_image', models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_codes/bookings/')),
                ('verification_code', models.CharField(help_text='Unique code for QR verification', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent to User'), ('scanned', 'Scanned'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('scan_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_by_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='QR code expiry time (usually checkout time)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='booking.booking')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_qr_codes', to='payment.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_booking_qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_code_booking_qrcode',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='qr_code_boo_booking_d4053e_idx'), models.Index(fields=['order'], name='qr_code_boo_order_i_8ca0e6_idx'), models.Index(fields=['verification_code'], name='qr_code_boo_verific_143ea9_idx'), models.Index(fields=['status'], name='qr_code_boo_status_210102_idx')],
            },
        ),
    ]
