# Generated by Django 5.2.5 on 2026-01-11 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        ('payment', '0002_initial'),
        ('qr_code', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingqrcode',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_booking_qr_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingqrcodelog',
            name='scanned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='qr_code.bookingqrcode'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderqrcode',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='payment.order'),
        ),
        migrations.AddField(
            model_name='orderqrcode',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_qr_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingqrcodelog',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='qr_code.orderqrcode'),
        ),
        migrations.AddIndex(
            model_name='bookingqrcode',
            index=models.Index(fields=['booking'], name='qr_code_boo_booking_d4053e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingqrcode',
            index=models.Index(fields=['order'], name='qr_code_boo_order_i_8ca0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingqrcode',
            index=models.Index(fields=['verification_code'], name='qr_code_boo_verific_143ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingqrcode',
            index=models.Index(fields=['status'], name='qr_code_boo_status_210102_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['booking', 'status'], name='qr_code_che_booking_049705_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['qr_code'], name='qr_code_che_qr_code_3a41fc_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['check_in_time'], name='qr_code_che_check_i_d19efc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['order'], name='qr_code_ord_order_i_187545_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['verification_code'], name='qr_code_ord_verific_ed1ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['status'], name='qr_code_ord_status_a4e24a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingqrcodelog',
            index=models.Index(fields=['qr_code', 'scanned_at'], name='qr_code_sca_qr_code_1baaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingqrcodelog',
            index=models.Index(fields=['scanned_by'], name='qr_code_sca_scanned_4fa7d5_idx'),
        ),
    ]
