# Generated by Django 5.2.5 on 2025-11-29 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_actual_check_in_time_and_more'),
        ('payment', '0001_initial'),
        ('qr_code', '0002_add_booking_qrcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(help_text='When user checked in')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='When user checked out', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of visit in minutes', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('check_in_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('check_out_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qr_code_checkin',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.AddField(
            model_name='bookingqrcode',
            name='is_currently_checked_in',
            field=models.BooleanField(default=False, help_text='True if user is currently checked in'),
        ),
        migrations.AddField(
            model_name='bookingqrcode',
            name='last_check_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingqrcode',
            name='last_check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingqrcode',
            name='max_check_ins',
            field=models.IntegerField(blank=True, help_text='Maximum allowed check-ins for monthly bookings', null=True),
        ),
        migrations.AddField(
            model_name='bookingqrcode',
            name='total_check_ins',
            field=models.IntegerField(default=0, help_text='Number of times checked in (for monthly tracking)'),
        ),
        migrations.AddField(
            model_name='bookingqrcode',
            name='used',
            field=models.BooleanField(default=False, help_text='True after final checkout (hourly/daily) or booking period ends (monthly)'),
        ),
        migrations.AlterField(
            model_name='bookingqrcode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent to User'), ('active', 'Active - Checked In'), ('verified', 'Verified - Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookingqrcode',
            index=models.Index(fields=['used'], name='qr_code_boo_used_0ac24c_idx'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checked_in_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_check_outs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkin',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='qr_code.bookingqrcode'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['booking', 'check_in_time'], name='qr_code_che_booking_89c781_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['qr_code'], name='qr_code_che_qr_code_7ff014_idx'),
        ),
    ]
