# Generated by Django 5.2.5 on 2025-11-29 14:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_bookingavailability_space_and_more'),
        ('qr_code', '0003_checkin_bookingqrcode_is_currently_checked_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QRCodeScanLog',
            new_name='BookingQRCodeLog',
        ),
        migrations.RemoveIndex(
            model_name='bookingqrcode',
            name='qr_code_boo_used_0ac24c_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkin',
            name='qr_code_che_booking_89c781_idx',
        ),
        migrations.RenameIndex(
            model_name='checkin',
            new_name='qr_code_che_qr_code_3a41fc_idx',
            old_name='qr_code_che_qr_code_7ff014_idx',
        ),
        migrations.RemoveField(
            model_name='bookingqrcode',
            name='is_currently_checked_in',
        ),
        migrations.RemoveField(
            model_name='bookingqrcode',
            name='last_check_in_at',
        ),
        migrations.RemoveField(
            model_name='bookingqrcode',
            name='last_check_out_at',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='check_in_ip',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='check_out_ip',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='checked_in_by',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='checked_out_by',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='checkin',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of stay (auto-calculated after checkout)', null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='checked_in', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingqrcode',
            name='max_check_ins',
            field=models.IntegerField(blank=True, help_text='Maximum check-ins allowed (for monthly bookings)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bookingqrcode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent to User'), ('scanned', 'Scanned'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingqrcode',
            name='total_check_ins',
            field=models.IntegerField(default=0, help_text='Total check-in events (for monthly bookings)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bookingqrcode',
            name='used',
            field=models.BooleanField(default=False, help_text='True after booking is completed/checked out'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_in_time',
            field=models.DateTimeField(help_text='When the user checked in'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='When the user checked out', null=True),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['booking', 'status'], name='qr_code_che_booking_049705_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['check_in_time'], name='qr_code_che_check_i_d19efc_idx'),
        ),
        migrations.AlterModelTable(
            name='checkin',
            table='qr_code_check_in',
        ),
    ]
