# Generated by Django 5.2.5 on 2025-12-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qr_code", "0004_rename_qrcodescanlog_bookingqrcodelog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingqrcode",
            name="qr_code_image",
        ),
        migrations.RemoveField(
            model_name="orderqrcode",
            name="qr_code_image",
        ),
        migrations.AddField(
            model_name="bookingqrcode",
            name="appwrite_file_id",
            field=models.CharField(
                blank=True,
                help_text="File ID in Appwrite storage",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bookingqrcode",
            name="qr_code_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to QR code image stored in Appwrite",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderqrcode",
            name="appwrite_file_id",
            field=models.CharField(
                blank=True,
                help_text="File ID in Appwrite storage",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderqrcode",
            name="qr_code_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to QR code image stored in Appwrite",
                null=True,
            ),
        ),
    ]
