# Generated by Django 5.2.5 on 2026-01-11 13:14

import booking.models
import core.mixins
import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('booking_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the booking')),
                ('start_time', models.TimeField(default=booking.models.default_start_time, help_text='Start time of the booking')),
                ('end_time', models.TimeField(default=booking.models.default_end_time, help_text='End time of the booking')),
                ('check_in', models.DateTimeField(help_text='Check-in datetime')),
                ('check_out', models.DateTimeField(help_text='Check-out datetime')),
                ('number_of_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_checked_in', models.BooleanField(default=False, help_text='Whether user has checked in')),
                ('is_checked_out', models.BooleanField(default=False, help_text='Whether user has checked out')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether check-in reminder email was sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_booking',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(help_text='Rating from 1-5', validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_review',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('item_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'booking_cart',
            },
            bases=(core.mixins.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the booking')),
                ('start_time', models.TimeField(default=booking.models.default_start_time, help_text='Start time of the booking')),
                ('end_time', models.TimeField(default=booking.models.default_end_time, help_text='End time of the booking')),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('number_of_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('special_requests', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_cart_item',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_checkout',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - QR code sent'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='pending', max_length=20)),
                ('qr_code_sent', models.BooleanField(default=False)),
                ('qr_code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_verification_code', models.CharField(default=booking.models.generate_verification_code, help_text='Unique verification code for guest QR', max_length=50, unique=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether check-in reminder email was sent')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False, help_text='Whether checkout receipt email was sent')),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_guest',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(help_text='Reservation start datetime')),
                ('end', models.DateTimeField(help_text='Reservation end datetime')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When this reservation expires')),
            ],
            options={
                'db_table': 'booking_reservation',
                'ordering': ['-created_at'],
            },
        ),
    ]
