# Generated by Django 5.2.5 on 2025-10-21 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('user', '0005_user_force_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting Verification'), ('verified', 'Verified - QR code sent'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('rejected', 'Rejected by Admin')], default='pending', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Admin Verification'), ('verified', 'Verified by Admin'), ('rejected', 'Rejected by Admin')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejecting guest', null=True)),
                ('qr_code_sent', models.BooleanField(default=False)),
                ('qr_code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code_verification_code', models.CharField(help_text='Unique verification code for guest QR', max_length=50, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='booking.booking')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_guests', to='user.user')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guests', to='user.user')),
            ],
            options={
                'db_table': 'booking_guest',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='booking_gue_booking_c84dd7_idx'), models.Index(fields=['email'], name='booking_gue_email_575941_idx'), models.Index(fields=['qr_code_verification_code'], name='booking_gue_qr_code_f704ae_idx')],
            },
        ),
    ]
