# Generated by Django 5.1.6 on 2025-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_guest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='guest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='verified_by',
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - QR code sent'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='workspace',
        ),
    ]
