# Generated by Django 5.2.5 on 2026-01-22 03:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('user_request', 'User Request'), ('change_of_plans', 'Change of Plans'), ('found_alternative', 'Found Alternative'), ('emergency', 'Emergency'), ('workspace_issue', 'Workspace Issue'), ('admin_cancellation', 'Admin Cancellation'), ('other', 'Other')], default='user_request', max_length=50)),
                ('reason_description', models.TextField(help_text='Detailed reason for cancellation')),
                ('workspace_issues', models.JSONField(blank=True, default=list, help_text='List of issues experienced with the workspace')),
                ('found_alternative', models.BooleanField(default=False, help_text='Whether user found an alternative workspace')),
                ('alternative_reason', models.TextField(blank=True, help_text='What made the alternative workspace better', null=True)),
                ('would_book_again', models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], help_text='Whether user would book this workspace again', max_length=10, null=True)),
                ('suggestions', models.TextField(blank=True, help_text='User suggestions for workspace improvement', null=True)),
                ('rating_before_cancellation', models.IntegerField(blank=True, help_text='User rating before cancellation (1-5)', null=True)),
                ('contacted_workspace', models.BooleanField(default=False, help_text='Whether user contacted workspace before cancelling')),
                ('workspace_response_satisfactory', models.BooleanField(blank=True, help_text='Whether workspace response was satisfactory', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('refund_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of original amount to refund', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Actual refund amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount deducted as penalty', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('refund_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('refund_reference', models.CharField(blank=True, help_text='Transaction reference for refund', max_length=100, null=True)),
                ('hours_until_checkin', models.DecimalField(decimal_places=2, help_text='Hours between cancellation and check-in time', max_digits=10)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin', null=True)),
                ('cancellation_email_sent', models.BooleanField(default=False)),
                ('refund_email_sent', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved the cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancellations', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_detail', to='booking.booking')),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_cancellation',
                'ordering': ['-cancelled_at'],
                'indexes': [models.Index(fields=['booking'], name='booking_can_booking_b2b0ec_idx'), models.Index(fields=['cancelled_by', 'status'], name='booking_can_cancell_9ff1a1_idx'), models.Index(fields=['status', 'refund_status'], name='booking_can_status_1d2a4c_idx'), models.Index(fields=['-cancelled_at'], name='booking_can_cancell_91a517_idx')],
            },
        ),
    ]
