# Generated by Django 5.1.6 on 2025-11-28 18:14

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reservation_cartitem_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='qr_code_verification_code',
            field=models.CharField(default=booking.models.generate_verification_code, help_text='Unique verification code for guest QR', max_length=50, unique=True),
        ),
    ]
