# Generated by Django 5.2.5 on 2025-11-29 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_guest_verification_code_default'),
        ('workspace', '0004_space_time_interval_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_check_in_time',
            field=models.DateTimeField(blank=True, help_text='Actual time user checked in', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='actual_check_out_time',
            field=models.DateTimeField(blank=True, help_text='Actual time user checked out', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, help_text='The date of the booking', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for monthly bookings', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of the booking slot', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_checked_in',
            field=models.BooleanField(default=False, help_text='Whether user has checked in'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_checked_out',
            field=models.BooleanField(default=False, help_text='Whether user has checked out'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for monthly bookings', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of the booking slot', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='booking_date',
            field=models.DateField(blank=True, help_text='The date of the booking', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of the booking slot', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of the booking slot', null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date', 'start_time'], name='booking_boo_booking_e54c0f_idx'),
        ),
    ]
