# Generated by Django 5.2.5 on 2025-11-29 14:45

import booking.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_actual_check_in_time_and_more'),
        ('workspace', '0004_space_time_interval_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingavailability',
            name='space',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_booking_e54c0f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='actual_check_in_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='actual_check_out_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='booking_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(help_text='Check-in datetime'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(help_text='Check-out datetime'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=booking.models.default_end_time, help_text='End time of the booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=booking.models.default_start_time, help_text='Start time of the booking'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the booking'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='end_time',
            field=models.TimeField(default=booking.models.default_end_time, help_text='End time of the booking'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='start_time',
            field=models.TimeField(default=booking.models.default_start_time, help_text='Start time of the booking'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'space', 'booking_date', 'start_time', 'end_time', 'booking_type')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='booking_boo_booking_737059_idx'),
        ),
        migrations.DeleteModel(
            name='BookingAvailability',
        ),
    ]
