# Generated by Django 5.2.5 on 2025-12-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_guest_receipt_sent_guest_receipt_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether check-in reminder email was sent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
