# Generated by Django 5.1.6 on 2025-12-11 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_reminder_sent_booking_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookings', models.ManyToManyField(blank=True, related_name='checkouts', to='booking.booking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_checkout',
                'ordering': ['-updated_at'],
            },
        ),
    ]
