# Generated by Django 5.1.6 on 2025-12-11 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_checkout'),
        ('workspace', '0005_remove_space_availability_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='workspace.spacecalendarslot'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='workspace.spacecalendarslot'),
        ),
    ]
