# Generated by Django 5.2.5 on 2026-01-11 13:14

import core.mixins
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours for each day of the week')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of branch photo URLs')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_branch',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('space_type', models.CharField(choices=[('meeting_room', 'Meeting Room'), ('office', 'Office'), ('coworking', 'Coworking Space'), ('event_space', 'Event Space'), ('desk', 'Dedicated Desk'), ('lounge', 'Lounge')], max_length=50)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rules', models.TextField(blank=True, help_text='Usage rules and guidelines for the space', null=True)),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy and refund rules', null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='workspace.branch')),
            ],
            options={
                'db_table': 'workspace_space',
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
            bases=(core.mixins.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SpaceCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_interval_minutes', models.IntegerField(default=60, help_text='Time slot interval in minutes (e.g., 60 for hourly slots)')),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours by day (0=Sunday, 6=Saturday)')),
                ('hourly_enabled', models.BooleanField(default=True)),
                ('daily_enabled', models.BooleanField(default=True)),
                ('monthly_enabled', models.BooleanField(default=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('daily_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_advance_booking_days', models.IntegerField(default=0, help_text='Minimum days in advance to book')),
                ('max_advance_booking_days', models.IntegerField(default=365, help_text='Maximum days in advance to book')),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='workspace.space')),
            ],
            options={
                'db_table': 'workspace_space_calendar',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('social_media_links', models.JSONField(blank=True, default=dict, help_text='Store social media links as key-value pairs')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.CachedModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='branch',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workspace.workspace'),
        ),
        migrations.CreateModel(
            name='SpaceCalendarSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the slot')),
                ('start_time', models.TimeField(help_text='Start time of the slot')),
                ('end_time', models.TimeField(help_text='End time of the slot')),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], help_text='Type of booking for this slot', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Reason for blocking/maintenance', null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_slots', to='booking.booking')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workspace.spacecalendar')),
            ],
            options={
                'db_table': 'workspace_space_calendar_slot',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['calendar', 'date', 'status'], name='workspace_s_calenda_5186b0_idx'), models.Index(fields=['booking'], name='workspace_s_booking_f13d5e_idx')],
                'unique_together': {('calendar', 'date', 'start_time', 'booking_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('workspace', 'name')},
        ),
        migrations.CreateModel(
            name='WorkspaceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('user', 'User')], default='staff', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspace.workspace')),
            ],
            options={
                'db_table': 'workspace_user',
                'ordering': ['-joined_at'],
                'unique_together': {('workspace', 'user')},
            },
        ),
    ]
