# Generated by Django 5.2.5 on 2026-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecalendarslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
