# Generated by Django 5.2.5 on 2025-11-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_alter_workspaceuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='hourly_rate',
            new_name='price_per_hour',
        ),
        migrations.AddField(
            model_name='branch',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of branch photo URLs'),
        ),
        migrations.AddField(
            model_name='branch',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours for each day of the week'),
        ),
        migrations.AddField(
            model_name='space',
            name='availability_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Custom availability schedule'),
        ),
        migrations.AddField(
            model_name='space',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Cancellation policy and refund rules', null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='operational_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Operating hours for each day of the week'),
        ),
        migrations.AddField(
            model_name='space',
            name='rules',
            field=models.TextField(blank=True, help_text='Usage rules and guidelines for the space', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='Store social media links as key-value pairs'),
        ),
    ]
