# Generated by Django 5.2.5 on 2025-11-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_rename_hourly_rate_space_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='time_interval_minutes',
            field=models.IntegerField(default=60, help_text='Slot interval in minutes'),
        ),
    ]
