# Generated by Django 5.2.5 on 2025-11-29 14:45

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_bookingavailability_space_and_more'),
        ('workspace', '0004_space_time_interval_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='availability_schedule',
        ),
        migrations.RemoveField(
            model_name='space',
            name='operational_hours',
        ),
        migrations.RemoveField(
            model_name='space',
            name='time_interval_minutes',
        ),
        migrations.CreateModel(
            name='SpaceCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_interval_minutes', models.IntegerField(default=60, help_text='Time slot interval in minutes (e.g., 60 for hourly slots)')),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours by day (0=Sunday, 6=Saturday)')),
                ('hourly_enabled', models.BooleanField(default=True)),
                ('daily_enabled', models.BooleanField(default=True)),
                ('monthly_enabled', models.BooleanField(default=True)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('daily_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_advance_booking_days', models.IntegerField(default=0, help_text='Minimum days in advance to book')),
                ('max_advance_booking_days', models.IntegerField(default=365, help_text='Maximum days in advance to book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='workspace.space')),
            ],
            options={
                'db_table': 'workspace_space_calendar',
            },
        ),
        migrations.CreateModel(
            name='SpaceCalendarSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the slot')),
                ('start_time', models.TimeField(help_text='Start time of the slot')),
                ('end_time', models.TimeField(help_text='End time of the slot')),
                ('booking_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], help_text='Type of booking for this slot', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Reason for blocking/maintenance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_slots', to='booking.booking')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workspace.spacecalendar')),
            ],
            options={
                'db_table': 'workspace_space_calendar_slot',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['calendar', 'date', 'status'], name='workspace_s_calenda_5186b0_idx'), models.Index(fields=['booking'], name='workspace_s_booking_f13d5e_idx')],
                'unique_together': {('calendar', 'date', 'start_time', 'booking_type')},
            },
        ),
    ]
