"""
Django settings for Xbooking project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-m(*^j-pbbi4$@-_wkjs=#trl5d%1m&8*4d&p-3zhh=w$la#nir')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    "core.apps.CoreConfig",  # Core utilities (must be before other apps)
    "user",
    "workspace",
    "booking",
    "payment",
    "bank",
    "qr_code",
    "notifications",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",
    "drf_spectacular",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.DisableCSRFForAPIMiddleware',  # Disable CSRF for /api/ endpoints
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Xbooking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Xbooking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL from environment variable, fallback to SQLite for development
DATABASES = {
    "default": dj_database_url.config(
        default=config("DATABASE_URL"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = 'user.User'

# Email Configuration
# EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

# Mailjet Configuration
# MAILJET_API_KEY = config('MAILJET_API_KEY', default='')
# MAILJET_SECRET_KEY = config('MAILJET_SECRET_KEY', default='')


# # SMTP Configuration (for Mailjet)
# if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
#     EMAIL_HOST = config('EMAIL_HOST', default='in-v3.mailjet.com')
#     EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
#     EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
#     EMAIL_HOST_USER = MAILJET_API_KEY
#     EMAIL_HOST_PASSWORD = MAILJET_SECRET_KEY

# Default From Email
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='shoabdulazeez@gmail.com')



# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

# If CORS_ALLOW_ALL_ORIGINS is False, use specific origins
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS', 
        default='http://localhost:3000,http://127.0.0.1:3000',
        cast=lambda v: [s.strip() for s in v.split(',')]
    )


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=config('ACCESS_TOKEN_LIFETIME_MINUTES', default=30, cast=int)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=config('REFRESH_TOKEN_LIFETIME_DAYS', default=1, cast=int)),
    "ROTATE_REFRESH_TOKENS": config('ROTATE_REFRESH_TOKENS', default=True, cast=bool),
    "BLACKLIST_AFTER_ROTATION": config('BLACKLIST_AFTER_ROTATION', default=True, cast=bool),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "JTI_CLAIM": "jti",
}

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.UUIDJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Use our custom pagination classes from core
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    # Use our custom throttle classes from core
    'DEFAULT_THROTTLE_CLASSES': [
        'core.throttling.AnonSustainedThrottle',
        'core.throttling.UserSustainedThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon_sustained': '100/day',
        'anon_burst': '10/minute',
        'user_sustained': '1000/day',
        'user_burst': '60/minute',
        'public_list': '20/minute',
        'sensitive_action': '5/minute',
        'file_upload': '50/day',
    },
    # Default renderer classes
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Exception handling
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Xbooking API',
    'DESCRIPTION': 'Workspace and space booking management API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Development Server'},
        {'url': 'https://backend.xbooking.dev', 'description': 'Production Server'},
        {'url': 'https://xbooking-backend.onrender.com', 'description': 'Render Deployment'},
    ],
    'CONTACT': {
        'name': 'Xbooking Support',
        'email': 'support@xbooking.dev',
    },

    # 👇 This is what makes the "Authorize" button work
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },

    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT Authorization using the Bearer scheme. Example: "Authorization: Bearer <token>"',
            },
        },
    },
}


# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Redis Cache Configuration (optional, for caching)
CACHES =  { 
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://localhost:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Redis Configuration for EventBus
REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=1, cast=int)

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Payment Gateway Configuration
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='')
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='')

FLUTTERWAVE_SECRET_KEY = config('FLUTTERWAVE_SECRET_KEY', default='')
FLUTTERWAVE_PUBLIC_KEY = config('FLUTTERWAVE_PUBLIC_KEY', default='')

# Payment settings
PAYMENT_CURRENCY = 'NGN'
PAYMENT_TIMEOUT = 3600  # 1 hour in seconds

# Redirect URLs for payment and deposit (set in .env)
DEPOSIT_REDIRECT_URL = config('DEPOSIT_REDIRECT_URL', default='')
PAYMENT_REDIRECT_URL = config('PAYMENT_REDIRECT_URL', default='')

# ============================================================================
# APPWRITE CLOUD STORAGE CONFIGURATION
# ============================================================================

# Appwrite Cloud Storage (for QR codes, images, documents, etc.)
APPWRITE_ENDPOINT = config('APPWRITE_ENDPOINT', default='https://cloud.appwrite.io/v1')
APPWRITE_PROJECT_ID = config('APPWRITE_PROJECT_ID', default='')
APPWRITE_API_KEY = config('APPWRITE_API_KEY', default='')
APPWRITE_BUCKET_ID = config('APPWRITE_BUCKET_ID', default='')

# ============================================================================
# FILE UPLOAD CONFIGURATION
# ============================================================================

# File upload API key for frontend authentication (unauthenticated endpoint)
FILE_UPLOAD_KEY = config('FILE_UPLOAD_KEY', default='')

# Max file size in MB for uploads
MAX_FILE_SIZE_MB = config('MAX_FILE_SIZE_MB', default=50, cast=int)

# Allowed file types for uploads
ALLOWED_FILE_TYPES = config(
    'ALLOWED_FILE_TYPES', 
    default='png,jpg,jpeg,gif,pdf,doc,docx,xls,xlsx',
    cast=lambda v: [s.strip().lower() for s in v.split(',')]
)

CSRF_TRUSTED_ORIGINS = [
    "https://d991097cf9a5.ngrok-free.app",
    "https://fb16c5785973.ngrok-free.app",
    "https://b9f13bfcc7a5.ngrok-free.app",
    "https://6a63f43d1a91.ngrok-free.app ",
    "https://3e9d98bfbd96.ngrok-free.app",
    "https://backend.xbooking.dev",
    "https://test-backend.xbooking.dev",
]

# ============================================================================
# EMAIL CONFIGURATION (MAILJET REST API)
# ============================================================================

# Mailjet REST API Configuration
MAILJET_API_KEY = config('MAILJET_API_KEY', default='')
MAILJET_SECRET_KEY = config('MAILJET_SECRET_KEY', default='')

# Default From Email
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='shoabdulazeez@gmail.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Note: We use Mailjet REST API instead of SMTP for better deliverability on VPS
# All email sending is handled through Xbooking.mailjet_utils.MailjetEmailService

# ============================================================================
# CLOUDINARY CONFIGURATION
# ============================================================================

CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')
CLOUDINARY_QR_FOLDER = config('CLOUDINARY_QR_FOLDER', default='xbooking/qr')
CLOUDINARY_UPLOAD_FOLDER = config('CLOUDINARY_UPLOAD_FOLDER', default='xbooking/uploads')
